name: goconcert
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^8.1.6
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.1.0
  flutter_svg: ^0.22.0
  image_picker: ^0.8.3+4
  # firebase_ml_vision: ^0.12.0
  camera: ^0.10.5+5
  google_mlkit_text_recognition: ^0.11.0
  google_ml_kit: ^0.16.3
  nik_validator: ^1.1.2
  provider: ^6.1.1
  flutter_exif_rotation: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/img/background.png
    - assets/img/chevron-left-solid.svg
    - assets/img/NewJeans-banner.png
    - assets/img/LeSserafim-banner.png
    - assets/img/Coldplay-banner.png
    - assets/img/bmth-banner.png
    - assets/img/singer.png
    - assets/img/bell.png
    - assets/img/search.png
    - assets/img/NewJeans.png
    - assets/img/LeSserafim.png
    - assets/img/bmth.jpeg
    - assets/img/coldplay.jpeg
    - assets/img/left-chevron.png
    

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf

