name: goconcert
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  camera: ^0.10.5+5
  cloud_firestore: ^4.13.2
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.14.1
  firebase_core: ^2.23.0
  firebase_storage: ^11.5.2
  flutter:
    sdk: flutter
  flutter_exif_rotation: ^0.5.1
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  google_ml_kit: ^0.16.3
  google_mlkit_text_recognition: ^0.11.0
  image: 3.1.3
  image_picker: ^0.8.3+4
  nik_validator: ^1.1.2
  permission_handler: ^8.1.6
  provider: ^6.1.1
  barcode_widget: ^2.0.4
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/background.png
    - assets/img/chevron-left-solid.svg
    - assets/img/NewJeans-banner.png
    - assets/img/LeSserafim-banner.png
    - assets/img/Coldplay-banner.png
    - assets/img/bmth-banner.png
    - assets/img/singer.png
    - assets/img/bell.png
    - assets/img/search.png
    - assets/img/NewJeans.png
    - assets/img/LeSserafim.png
    - assets/img/bmth.jpeg
    - assets/img/coldplay.jpeg
    - assets/img/left-chevron.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
